[profile.default]
src = "src"
script = "script"
out = "out"
libs = ["lib", "node_modules"]
solc_version = '0.8.25'

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 132
multiline_func_header = "all"
number_underscore = "preserve"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
